### PR TITLE
Hotkey File & Hotkey Setting GUI

### PR DESCRIPTION
**Pull request by chasemcdizzle**
Multiple Features Added:
-Note that smashbox-gui.ahk is a complete standalone replacement to the
original .ahk script.

1. Program reads hotkeys from a file, that way people can customize, and
save hotkeys as they please, and people can distribute their own hotkey
files to others (see Hotkeys.ini after running the program for the first
time).

2. GUI included for the user to map their own hotkeys, which are saved
to file. Hotkey changes are reflected immediately, in real time, and
also saved to file immediately.

3. x/y and units and analog units are now set by absolute value, rather
than percent. The values have been changed to be 100% accurate to the
smashbox (except lightshield). Currently they are set to Project M
values, likely to add a switch on the GUI to be able to switch between
Project M mode and Melee mode.

4. user can decide if they want the hotkeys they set to still perform
their expected default procedure. i.e. setting a hotkey to the letter
'f' and leaving "Prevent Default Behavior" checkbox  unchecked will
result in the script both performing the desired vJoy input, as well as
still typing the letter F. User can turn this off as well, if, for
example, they are binding to something like the escape key.

5. Key combination ctrl+alt+s will Toggle hotkeys enabled.

6. Key combination ctrl+alt+r will cause the script to reload from
source. Useful for development to quickly reload the script after
changing the source.

### CODE REVIEW

**Comment by tlandegger** [comment]
I get this error when trying to run the script.
capture

**Comment by chasemcdizzle** [comment]
My mistake. I made a change to the code that requires Hotkeys.ini to be in the same directory when you boot it. Previously if the file wasn't there it would just create it, I'll have to go back and make it like that again in the future.

I added a default Hotkeys.ini for now and pushed the changes. Also I will be adding a switch on the GUI that will let you switch between Melee and Project M, as well as a toggle all checkboxes button.

**Comment by chasemcdizzle** [comment]
Also this may not be 100% ready for main branch because it's currently hard coded for JUST Project M, but I figured I'd go ahead and do a pull request just to show you what I did yesterday. If you have Discord we should chat, my username is chasemcdizzle#1511

**Comment by tlandegger** [comment]
Merging then updating with melee values and code refactoring

**Pull request merged**
